[project]
name = "krice"
version = "0.1.0"
description = "Modern KDE Plasma 6 ricing, fluid motion & multi-machine sync toolkit"
readme = "README.md"
authors = [
    { name = "vesita", email = "vesita164872@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "konsave>=2.3.0",
    "pyyaml>=6.0.3",
    "rich>=15.0.0",
    "typer>=0.27.2",
]

[project.scripts]
krice = "krice:main"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
