"""Generates shell prompt (Starship) and fetch tool (Fastfetch) configurations matching palettes."""

from __future__ import annotations

import json
from krice.presets.terminal_palettes import TerminalPalette


def generate_starship_config(palette: TerminalPalette) -> str:
    """Generates a modern pill-styled starship.toml configuration tailored to the color palette."""
    bg_pill_1 = palette.cyan if palette.is_dark else palette.blue
    fg_pill_1 = palette.background if palette.is_dark else palette.foreground
    bg_pill_2 = palette.selection_bg
    fg_pill_2 = palette.foreground
    accent_blue = palette.blue
    accent_green = palette.green
    accent_yellow = palette.yellow
    accent_magenta = palette.magenta
    accent_red = palette.red

    return f"""# Starship Prompt - Generated by krice for {palette.display_name}

format = \"\"\"
[]({bg_pill_1})\\
[  ](bg:{bg_pill_1} fg:{fg_pill_1})\\
[](bg:{bg_pill_2} fg:{bg_pill_1})\\
$directory\\
[](fg:{bg_pill_2} bg:{palette.selection_bg})\\
$git_branch\\
$git_status\\
[](fg:{palette.selection_bg} bg:{bg_pill_2})\\
$rust\\
$golang\\
$python\\
$nodejs\\
[](fg:{bg_pill_2} bg:{palette.selection_bg})\\
$cmd_duration\\
[ ](fg:{palette.selection_bg})\\
$character
\"\"\"

command_timeout = 800

[directory]
style = "fg:{fg_pill_2} bg:{bg_pill_2} bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "fg:{accent_blue} bg:{palette.selection_bg} bold"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:{accent_yellow} bg:{palette.selection_bg}"
format = "[$all_status$ahead_behind ]($style)"

[rust]
symbol = ""
style = "fg:{accent_red} bg:{bg_pill_2} bold"
format = "[ $symbol ($version) ]($style)"

[golang]
symbol = ""
style = "fg:{accent_blue} bg:{bg_pill_2} bold"
format = "[ $symbol ($version) ]($style)"

[python]
symbol = ""
style = "fg:{accent_green} bg:{bg_pill_2} bold"
format = "[ $symbol ($version) ]($style)"

[nodejs]
symbol = ""
style = "fg:{accent_green} bg:{bg_pill_2} bold"
format = "[ $symbol ($version) ]($style)"

[cmd_duration]
min_time = 500
style = "fg:{accent_blue} bg:{palette.background}"
format = "[ ⏱ $duration ]($style)"

[character]
success_symbol = "[❯](bold {accent_blue})"
error_symbol = "[❯](bold {accent_red})"
"""


def generate_fastfetch_config(palette: TerminalPalette) -> str:
    """Generates a clean fastfetch config.jsonc matching the palette."""
    key_color = "cyan" if palette.is_dark else "blue"
    title_color = "blue" if palette.is_dark else "cyan"

    # Map closest ANSI color name or color index
    config = {
        "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
        "logo": {
            "type": "small",
            "color": {
                "1": key_color,
                "2": title_color,
            },
            "padding": {
                "top": 1,
                "left": 2,
            },
        },
        "display": {
            "separator": " 󰅂 ",
            "color": {
                "keys": key_color,
                "title": title_color,
            },
        },
        "modules": [
            "title",
            {
                "type": "custom",
                "format": "──────────────────────────────",
            },
            {"type": "os", "key": "OS", "keyColor": key_color},
            {"type": "kernel", "key": "Kernel", "keyColor": key_color},
            {"type": "de", "key": "DE", "keyColor": key_color},
            {"type": "wm", "key": "WM", "keyColor": key_color},
            {"type": "terminal", "key": "Terminal", "keyColor": key_color},
            {"type": "shell", "key": "Shell", "keyColor": key_color},
            {"type": "cpu", "key": "CPU", "keyColor": title_color},
            {"type": "gpu", "key": "GPU", "keyColor": title_color},
            {"type": "memory", "key": "Memory", "keyColor": title_color},
            {"type": "colors", "symbol": "circle"},
        ],
    }
    return json.dumps(config, indent=2) + "\n"
